name: Dependency check

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 2 * * *'

jobs:
  latest-python:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v2

      - name: install lib
        run: pip install -e .

  minimum-python:
    runs-on: ubuntu-latest
    container:
      image: python:3.6

    steps:
      - uses: actions/checkout@v2

      - name: install lib
        run: pip install -e .
